esphome:
  name: esphome-xgt
  friendly_name: esphome-xgt

  on_boot:
    then:
      # Turn on backlight and power to neopixel
      - output.turn_on: backlight_output
      - output.turn_on: neopixel_power

esp32:
  board: lolin_s3_mini
  variant: esp32s3
  flash_size: 4MB
  framework:
    type: esp-idf

psram:

logger:
  level: DEBUG

api:
  reboot_timeout: 0s #disable auto 15min reboot with no HA connection
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  reboot_timeout: 0s #disable reboot if no wifi - Defaults to 15min. Does not apply when in access point mode.
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  ap: # Enable fallback hotspot (captive portal) in case wifi connection fails
    ssid: "esphome-xgt"
    password: "password"

captive_portal:

# Platform components required by xgt_battery
sensor:

text_sensor:

# External Components
external_components:
  - source:
      type: git
      url: https://github.com/ssieb/esphome
      ref: uarthalf
    components: [ uart ]
    refresh: 0s
  - source: components
    components: [xgt_battery]

# New UART configuration with half-duplex support
uart:
  - id: xgt_uart
    baud_rate: 9600
    half_duplex: true
    parity: EVEN          # CRITICAL: Must be EVEN parity (8E1)
    tx_pin: 
      number: GPIO14
      inverted: true      # CRITICAL: Must be inverted

# XGT Battery Component
xgt_battery:
  id: xgt_batt
  uart_id: xgt_uart
  update_interval: 5s
  
  # Main battery sensors
  battery_voltage:
    name: "Battery Voltage"
    id: battery_voltage
    on_value:
      then:
        - lvgl.label.update:
            id: label_battery_voltage
            text: !lambda 'return str_sprintf("%.1fV", x);'
  battery_temperature:
    name: "Battery Temperature"
    id: battery_temperature
    on_value:
      then:
        - lvgl.label.update:
            id: label_battery_temp
            text: !lambda 'return str_sprintf("%.0f°C", x);'
  battery_charge:
    name: "Battery Charge"
    id: battery_charge
    on_value:
      then:
        - lvgl.label.update:
            id: label_battery_soc
            text: !lambda 'return str_sprintf("%.0f%%", x);'
  battery_health:
    name: "Battery Health"
    id: battery_health
    on_value:
      then:
        - lvgl.label.update:
            id: label_battery_soh
            text: !lambda 'return str_sprintf("SOH %.0f%%", x);'
  min_cell_voltage:
    name: "Min Cell Voltage"
    id: min_cell_voltage
    on_value:
      then:
        - lvgl.label.update:
            id: label_min_cell
            text: !lambda 'return str_sprintf("%.3fV", x);'
  max_cell_voltage:
    name: "Max Cell Voltage"
    id: max_cell_voltage
    on_value:
      then:
        - lvgl.label.update:
            id: label_max_cell
            text: !lambda 'return str_sprintf("%.3fV", x);'
  cell_divergence:
    name: "Cell Divergence"
    id: cell_divergence
    on_value:
      then:
        - lvgl.label.update:
            id: label_cell_diff
            text: !lambda 'return str_sprintf("%.0fmV", x * 1000);'
    
  # Diagnostic sensors
  num_charges:
    name: "Battery Charge Cycles"
    id: battery_cycles
    on_value:
      then:
        - lvgl.label.update:
            id: label_charge_cycles
            text: !lambda 'return str_sprintf("%.0f cycles", x);'
  cell_size:
    name: "Cell Capacity"
    id: cell_capacity
    on_value:
      then:
        - lvgl.label.update:
            id: label_cell_capacity
            text: !lambda 'return str_sprintf("%.0fmAh", x);'
  parallel_count:
    name: "Parallel Cell Count"
    id: parallel_cells
    on_value:
      then:
        - lvgl.label.update:
            id: label_parallel_count
            text: !lambda 'return str_sprintf("%.0fP", x);'
    
  # Cell voltages (all 10 cells)
  cell_voltage:
    cell_1:
      name: "Cell 1 Voltage"
      id: cell_1_voltage
    cell_2:
      name: "Cell 2 Voltage"
      id: cell_2_voltage
    cell_3:
      name: "Cell 3 Voltage"
      id: cell_3_voltage
    cell_4:
      name: "Cell 4 Voltage"
      id: cell_4_voltage
    cell_5:
      name: "Cell 5 Voltage"
      id: cell_5_voltage
    cell_6:
      name: "Cell 6 Voltage"
      id: cell_6_voltage
    cell_7:
      name: "Cell 7 Voltage"
      id: cell_7_voltage
    cell_8:
      name: "Cell 8 Voltage"
      id: cell_8_voltage
    cell_9:
      name: "Cell 9 Voltage"
      id: cell_9_voltage
    cell_10:
      name: "Cell 10 Voltage"
      id: cell_10_voltage

# Buttons
binary_sensor:

  - platform: gpio
    name: "Button - Left"
    pin:
      number: GPIO0
      inverted: true
      mode:
          input: true
          pullup: true

  - platform: gpio
    name: "Button - Middle"
    pin:
      number: GPIO47
      inverted: true
      mode:
          input: true
          pullup: true

          
  - platform: gpio
    name: "Button - Right"
    pin:
      number: GPIO48
      inverted: true
      mode:
          input: true
          pullup: true
    
# WS2812 LED
# PIN GPIO07 needs to be HIGH so it gets power


# Backlight and WS2812 Power Supply
output:
  - platform: gpio
    pin: GPIO07
    id: neopixel_power
  - platform: gpio
    pin: GPIO33
    id: backlight_output

spi:
  clk_pin: GPIO40
  mosi_pin: GPIO38

display:
  - platform: ili9xxx
    id: disp
    dimensions:
      height: 128
      width: 128
      offset_height: 1
      offset_width: 2
    model: st7789v
    data_rate: 80MHz
    cs_pin: GPIO35
    dc_pin: GPIO36
    reset_pin: GPIO34
    invert_colors: true
    #transform:
    #  mirror_x: true
    #  mirror_y: true
    update_interval: never
    auto_clear_enabled: false

lvgl:
    log_level: INFO
    color_depth: 16
    bg_color: 0
    border_width: 0
    outline_width: 0
    #shadow_width: 0
    text_font: unscii_16
    align: center
    style_definitions:
      - id: font_style
        text_font: MONTSERRAT_20
        #text_font: unscii_16
        align: center
        text_color: 0xFFFFFF
        #bg_opa: cover
        bg_opa: TRANSP
        bg_color: 0
        radius: 4
        pad_all: 1 
      - id: details_style
        text_font: MONTSERRAT_24
        align: center
        text_color: 0xFFFFFF
        #bg_opa: cover
        bg_opa: TRANSP
        bg_color: 0
        radius: 4
        pad_all: 1
      - id: small_font_style
        text_font: MONTSERRAT_16
        align: center
        text_color: 0xFFFFFF
        bg_opa: TRANSP
        bg_color: 0
        radius: 2
        pad_all: 1
      - id: large_font_style
        text_font: MONTSERRAT_28
        align: center
        text_color: 0xFFFFFF
        bg_opa: TRANSP
        bg_color: 0
        radius: 2
        pad_all: 1 
    page_wrap: true
    pages:
      - id: main_page
        widgets:
          - obj: # Main container
              height: 128
              width: 128
              align: center
              bg_color: 0
              border_width: 0
              outline_width: 0
              pad_all: 0
              scrollbar_mode: "off"
              widgets:
                # Pack Voltage - Top left
                - label:
                    styles: font_style
                    id: label_battery_voltage
                    y: -49
                    x: -29
                    text: "-.-V"
                    
                # Battery Charge % - Top right
                - label:
                    styles: large_font_style
                    id: label_battery_soc
                    y: -50
                    x: 35
                    text: "---%"
                    
                # Temperature - Left side  
                - label:
                    styles: small_font_style
                    id: label_battery_temp
                    y: -15
                    x: -39
                    text: "-.-°C"
                    
                # SOH (Battery Health) - Right side
                - label:
                    styles: small_font_style
                    id: label_battery_soh
                    y: -15
                    x: 25
                    text: "SOH ---%"
                    
                # Min Cell Voltage - Left middle
                - label:
                    styles: small_font_style
                    id: label_min_cell
                    y: 8
                    x: -35
                    text: "-.---V"
                    
                # Max Cell Voltage - Right middle
                - label:
                    styles: small_font_style
                    id: label_max_cell
                    y: 8
                    x: 35
                    text: "-.---V"
                    
                # Cell voltage difference - Left
                - label:
                    styles: small_font_style
                    id: label_cell_diff
                    y: 31
                    x: -35
                    text: "---mV"
                    
                # Charge cycles - Right
                - label:
                    styles: small_font_style
                    id: label_charge_cycles
                    y: 31
                    x: 30
                    text: "--- cycles"
                    
                # Cell capacity - Left bottom
                - label:
                    styles: small_font_style
                    id: label_cell_capacity
                    y: 54
                    x: -21
                    text: "---mAh"
                    
                # Parallel count - Right bottom
                - label:
                    styles: small_font_style
                    id: label_parallel_count
                    y: 54
                    x: 41
                    text: "---P"
 
    